bcdist: trusty
language: c
addons:
  apt:
    sources:
      - sourceline: ppa:team-gcc-arm-embedded/ppa
    packages:
      - gcc-arm-embedded
script:
  - make release OUT=bcf-radio-move-detector-x-axis-${TRAVIS_TAG} VERSION=${TRAVIS_TAG} AXIS_DETECTION=X
  - make release OUT=bcf-radio-move-detector-y-axis-${TRAVIS_TAG} VERSION=${TRAVIS_TAG} AXIS_DETECTION=Y
  - make release OUT=bcf-radio-move-detector-z-axis-${TRAVIS_TAG} VERSION=${TRAVIS_TAG} AXIS_DETECTION=Z
deploy:
  skip_cleanup: true
  file_glob: true
  file: out/release/*.bin
  api_key: ${GITHUB_KEY}
  provider: releases
  overwrite: true
  on:
    tags: true
